services:
  - type: web
    name: asterominer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn product:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
